export default {
  "login": "anthonyjwwong",
"id": 35710860,
"node_id": "MDQ6VXNlcjM1NzEwODYw",
"avatar_url": "https://avatars.githubusercontent.com/u/35710860?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/anthonyjwwong",
"html_url": "https://github.com/anthonyjwwong",
"followers_url": "https://api.github.com/users/anthonyjwwong/followers",
"following_url": "https://api.github.com/users/anthonyjwwong/following{/other_user}",
"gists_url": "https://api.github.com/users/anthonyjwwong/gists{/gist_id}",
"starred_url": "https://api.github.com/users/anthonyjwwong/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/anthonyjwwong/subscriptions",
"organizations_url": "https://api.github.com/users/anthonyjwwong/orgs",
"repos_url": "https://api.github.com/users/anthonyjwwong/repos",
"events_url": "https://api.github.com/users/anthonyjwwong/events{/privacy}",
"received_events_url": "https://api.github.com/users/anthonyjwwong/received_events",
"type": "User",
"site_admin": false,
"name": "Anthony Wong",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "Front-End Web Developer  ||          \r\n\r\n Anthony Wong\r\n",
"twitter_username": null,
"public_repos": 23,
"public_gists": 0,
"followers": 2,
"following": 2,
"created_at": "2018-01-22T23:45:51Z",
"updated_at": "2021-09-25T20:11:48Z"
};
